---
apiVersion: v1
kind: Service
metadata:
  name: results-service
  labels:
    app: results
spec:
  type: NodePort
  ports:
    - name: http
      port: 3002
      targetPort: 3002
      nodePort: 30002
  selector:
    app: results
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: results
  labels:
    app: results
spec:
  replicas: 3
  selector:
    matchLabels:
      app: results
  template:
    metadata:
      labels:
        app: results
    spec:
      containers:
        - name: results
          image: skylwalker1470/poll-app-results:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          env:
            - name: POLL_HOST
              value: poll-service
            - name: POLL_PORT
              value: "3000"
            - name: VOTE_HOST
              value: vote-service
            - name: VOTE_PORT
              value: "3001"
