---
apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    app: vote
spec:
  type: NodePort
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      nodePort: 30001
  selector:
    app: vote
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          image: skylwalker1470/poll-app-vote:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_HOST
              value: mongo-service
            - name: MONGO_PORT
              value: "27017"
            - name: POLL_HOST
              value: poll-service
            - name: POLL_PORT
              value: "3000"
